version: "3.8"

services:
   quorum-explorer:
      image: consensys/quorum-explorer:latest
      container_name: quorum-explorer
      mem_limit: "5g"
      restart: unless-stopped
      networks:
        - proxy
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./config.json:/app/config.json
        - ./.env.production:/app/.env.production
      # disable if not using traefik
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.quorum-explorer.entrypoints=http"
        - "traefik.http.routers.quorum-explorer.rule=Host(`quorum-explorer`)"
        - "traefik.http.routers.quorum-explorer-secure.entrypoints=https"
        - "traefik.http.routers.quorum-explorer-secure.rule=Host(`quorum-explorer`)"
        - "traefik.http.routers.quorum-explorer-secure.tls=true"
        - "traefik.http.routers.quorum-explorer-secure.tls.certresolver=http"
        - "traefik.http.routers.quorum-explorer-secure.service=quorum-explorer"
        - "traefik.http.services.quorum-explorer.loadbalancer.server.port=25000"
        - "traefik.docker.network=proxy"

# disable if not using traefik
networks:
  proxy:
    external: true
